
f"""
THESE ARE THE PARAMETERS THAT YOU NEED TO ADD:

- bot_token: The token that you obtained on telegram from the BotFather after creating your own telegram bot.
If you don't know how to get the token, refer to this link and follow the steps: 
https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token

- chat_id: Is the unique identification number of your telegram profile'
If you don't know how to get the id, refer to this link and follow the steps:
https://www.alphr.com/find-chat-id-telegram/

- sheets_link: Is the link generated by the sheety API service, that takes us to the Amazon price tracker google
sheets that you already created. If you don't know how to get the link, refer to the readme file of this project
"""

# INSERT TELEGRAM BOT TOKEN
bot_token = ""

# INSERT TELEGRAM CHAT ID
chat_id = ""

# INSERT GOOGLE SHEETS API ADDRESS
sheets_link = ""